# Note: it's important that none of the packages below depend on Astropy,
# because if they do, the conda version of Astropy will get installed. If that
# happens, then that version will take precendence over the latest developer
# version of Astropy that gets installed just before the documentation build,
# and Sphinx will pick up only the older stable conda package.

name: astropy

dependencies:
  - python=3.5*
  - numpy
  - cython
  - matplotlib
  - scipy
  - pillow
  - pyyaml
  - jinja2
  - h5py
  - scikit-image
  - pandas
  - pytz
  - beautifulsoup4
  - ipython
  - mpmath
  - pip:
    - sphinx-gallery>=0.1.9
    - jplephem
